### PR TITLE
Add this._super into hooks and improve ES6/Ember syntax

### PR DESCRIPTION
**Pull request by villander**
`this._super` as [best practices](https://guides.emberjs.com/v2.6.0/components/the-component-lifecycle/)

### CODE REVIEW

**Comment by knownasilya** [comment]
The only thing that I don't want to replace is `Array.isArray`, since that is supported by all browsers that Ember supports. Eventually I see Ember deprecating their version.

**Comment by villander** [comment]
Ok @knownasilya i will fix this

**Comment by villander** [comment]
Already @knownasilya 👍

**Comment by knownasilya** [comment]
Thanks!

**Comment by villander** [comment]
@knownasilya what about, of we create a ROADMAP to insert into your `addon` all available options this repo ? 
https://github.com/knownasilya/jquery-highlight

**Pull request merged**
